syntax = "proto3";

package mmo.protocol.v1;

option go_package = "github.com/example/mmo-server/internal/protocolpb/gen;protocolpb";

import "bag.proto";

message GmReloadRequest {
  string table_name = 1 [json_name = "tableName"];
  string operator = 2 [json_name = "operator"];
}

message GmReloadResponse {
  int64 version = 1 [json_name = "version"];
  int64 tables = 2 [json_name = "tables"];
}

message GmAccountQueryRequest {
  int64 uid = 1 [json_name = "uid"];
  string nickname = 2 [json_name = "nickname"];
}

message GmAccountView {
    int64 uid = 1 [json_name = "uid"];
    string nickname = 2 [json_name = "nickname"];
    int64 created_at_unix = 3 [json_name = "createdAtUnix"];
    bool banned = 4 [json_name = "banned"];
    string ban_reason = 5 [json_name = "banReason"];
    int64 banned_until = 6 [json_name = "bannedUntil"];
    bool muted = 7 [json_name = "muted"];
    string mute_reason = 8 [json_name = "muteReason"];
    int64 muted_until = 9 [json_name = "mutedUntil"];
}

message GmPlayerQueryRequest {
  int64 player_id = 1 [json_name = "playerId"];
  string name = 2 [json_name = "name"];
  int64 uid = 3 [json_name = "uid"];
}

message GmPlayerRecord {
  int64 player_id = 1 [json_name = "playerId"];
  int64 uid = 2 [json_name = "uid"];
  string name = 3 [json_name = "name"];
  bool deleted = 4 [json_name = "deleted"];
  int64 created_at_unix = 5 [json_name = "createdAtUnix"];
}

message GmPlayerQueryResponse {
  repeated GmPlayerRecord list = 1 [json_name = "list"];
}

message GmBagQueryRequest {
  int64 player_id = 1 [json_name = "playerId"];
  int32 bag_type = 2 [json_name = "bagType"];
}

message GmGrantRequest {
  int64 player_id = 1 [json_name = "playerId"];
  int32 item_id = 2 [json_name = "itemId"];
  int32 count = 3 [json_name = "count"];
  int32 bag_type = 4 [json_name = "bagType"];
  string operator = 5 [json_name = "operator"];
}

message GmGrantResponse {
  int32 bag_type = 1 [json_name = "bagType"];
  BagListResponse bag = 2 [json_name = "bag"];
  bool pushed = 3 [json_name = "pushed"];
}

message GmKickRequest {
  int64 uid = 1 [json_name = "uid"];
  int64 player_id = 2 [json_name = "playerId"];
  string operator = 3 [json_name = "operator"];
}

message GmKickResponse {
    int64 uid = 1 [json_name = "uid"];
    bool kicked = 2 [json_name = "kicked"];
}

message GmDeductRequest {
    int64 player_id = 1 [json_name = "playerId"];
    int32 item_id = 2 [json_name = "itemId"];
    int32 slot = 3 [json_name = "slot"];
    int32 count = 4 [json_name = "count"];
    int32 bag_type = 5 [json_name = "bagType"];
    string operator = 6 [json_name = "operator"];
}

message GmBanRequest {
    int64 uid = 1 [json_name = "uid"];
    string nickname = 2 [json_name = "nickname"];
    string reason = 3 [json_name = "reason"];
    string operator = 4 [json_name = "operator"];
    int64 duration_seconds = 5 [json_name = "durationSeconds"];
}

message GmBanResponse {
    int64 uid = 1 [json_name = "uid"];
    bool banned = 2 [json_name = "banned"];
    bool kicked = 3 [json_name = "kicked"];
    int64 banned_until = 4 [json_name = "bannedUntil"];
    bool tokens_revoked = 5 [json_name = "tokensRevoked"];
}

message GmMuteResponse {
    int64 uid = 1 [json_name = "uid"];
    bool muted = 2 [json_name = "muted"];
    int64 muted_until = 3 [json_name = "mutedUntil"];
}

message GmMaintenanceRequest {
    bool enabled = 1 [json_name = "enabled"];
    string reason = 2 [json_name = "reason"];
    string operator = 3 [json_name = "operator"];
}

message GmMaintenanceResponse {
    bool enabled = 1 [json_name = "enabled"];
    string reason = 2 [json_name = "reason"];
    int32 kicked = 3 [json_name = "kicked"];
}

message GmKickAllRequest {}

message GmKickAllResponse {
    int32 kicked = 1 [json_name = "kicked"];
}

message GmOnlineRequest {
    int32 scene_id = 1 [json_name = "sceneId"];
}

message GmOnlinePlayer {
    int64 uid = 1 [json_name = "uid"];
    int32 scene_id = 2 [json_name = "sceneId"];
}

message GmOnlineResponse {
    repeated GmOnlinePlayer list = 1 [json_name = "list"];
}

message GmNoticeRequest {
    int32 scene_id = 1 [json_name = "sceneId"];
    string text = 2 [json_name = "text"];
    string operator = 3 [json_name = "operator"];
}

message GmNoticeResponse {
    int32 pushed = 1 [json_name = "pushed"];
}

message GmNoticePush {
    string text = 1 [json_name = "text"];
    int32 scene_id = 2 [json_name = "sceneId"];
}

message GmTimeSetRequest {
    int64 bias_seconds = 1 [json_name = "biasSeconds"];
    string operator = 2 [json_name = "operator"];
}

message GmTimeGetResponse {
    int64 bias_seconds = 1 [json_name = "biasSeconds"];
    int64 unix_now = 2 [json_name = "unixNow"];
    int64 real_unix_now = 3 [json_name = "realUnixNow"];
}
